module.exports = [
  'Eddard "Ned" Stark',
  "Robert Baratheon",
  "Jaime Lannister",
  "Catelyn Stark",
  "Cersei Lannister",
  "Daenerys Targaryen",
  "Jorah Mormont",
  "Viserys Targaryen",
  "Jon Snow",
  "Sansa Stark",
  "Arya Stark",
  "Robb Stark",
  "Theon Greyjoy",
  "Bran Stark",
  "Joffrey Baratheon",
  'Sandor "The Hound" Clegane',
  "Tyrion Lannister",
  'Petyr "Littlefinger" Baelish',
  "Davos Seaworth",
  "Samwell Tarly",
  "Stannis Baratheon",
  "Melisandre",
  "Jeor Mormont",
  "Bronn",
  "Varys",
  "Shae",
  "Margaery Tyrell",
  "Tywin Lannister",
  "Talisa Maegyr",
  "Ygritte",
  "Gendry",
  "Tormund Giantsbane",
  "Brienne of Tarth",
  "Ramsay Bolton",
  "Gilly",
  "Daario Naharis",
  "Missandei",
  "Tommen Baratheon",
  "Ellaria Sand",
  "Jaqen H'ghar",
  "Roose Bolton",
  "The High Sparrow",
  "Grey Worm",
  "Khal Drogo",
  "Grand Maester Pycelle",
  "Meryn Trant",
  "Hodor",
  "Grenn",
  "Osha",
  "Rickon Stark",
  "Ros",
  "Gregor Clegane",
  "Janos Slynt",
  "Lancel Lannister",
  "Myrcella Baratheon",
  "Rodrik Cassel",
  "Maester Luwin",
  "Irri",
  "Doreah",
  "Renly Baratheon",
  "Yoren",
  "Kevan Lannister",
  "Ilyn Payne",
  "Barristan Selmy",
  "Walder Frey",
  "Maester Aemon",
  "Alliser Thorne",
  "Robin Arryn",
  "Benjen Stark",
  "Lysa Arryn",
  "Septa Mordane",
  "Jory Cassel",
  "Greatjon Umber",
  "Mirri Maz Duur",
  "Syrio Forel",
  "Loras Tyrell",
  "Hot Pie",
  "Rickard Karstark",
  "Beric Dondarrion",
  "Podrick Payne",
  "Eddison Tollett",
  "Yara Greyjoy",
  "Craster",
  "Dontos Hollard",
  "Xaro Xhoan Daxos",
  "Pyat Pree",
  "Qhorin Halfhand",
  "Spice King",
  "Silk King",
  "Alton Lannister",
  "Selyse Baratheon",
  "Qyburn",
  "Olenna Tyrell",
  "Shireen Baratheon",
  "Meera Reed",
  "Jojen Reed",
  "Locke",
  "Mance Rayder",
  "Edmure Tully",
  "Thoros of Myr",
  "Brynden Tully",
  "Kraznys mo Nakloz",
  "High Septon",
  "Myranda",
  "Olyvar",
  "Black Walder Rivers",
  "Olly",
  "Mace Tyrell",
  "Oberyn Martell",
  "Thenn warg",
  "Walda Bolton",
  "Hizdahr zo Loraq",
  "Yohn Royce",
  "Three-Eyed Raven",
  "Leaf",
  "Night King",
  "The Waif",
  "Septa Unella",
  "Tyene Sand",
  "Nymeria Sand",
  "Obara Sand",
  "Areo Hotah",
  "Doran Martell",
  "Trystane Martell",
  "Wun Wun",
  "Maester Wolkan",
  "Lyanna Mormont",
  "Harald Karstark",
  "Khal Moro",
  "Euron Greyjoy",
  "Robett Glover",
  "Randyll Tarly",
  "Dickon Tarly",
  "Archmaester Ebrose",
  "Harrag",
  "Alys Karstark",
];
